spring.application.name=pagamentos-api
spring.datasource.url=jdbc:mysql://${DB_HOST}/${DB_NAME}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show.sql=true

# URL do Eureka Server.
# O cliente utiliza esse endereço para localizar o Service Registry
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka

# Define um identificador único para cada instância do serviço no Eureka,
# combinando o nome da aplicação com um valor aleatório.
eureka.instance.instance-id=${spring.application.name}:${random.int}

# Porta em que a aplicação será executada.
# Ao usar "0", o Spring Boot atribui automaticamente uma porta aleatória disponível no sistema.
server.port=0