spring.application.name=pagamento-api
spring.datasource.url=jdbc:mysql://${DB_HOST}/${DB_NAME}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show.sql=true

# URL do Eureka Server.
# O cliente utiliza esse endereço para localizar o Service Registry
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka

# Define um identificador único para cada instância do serviço no Eureka,
# combinando o nome da aplicação com um valor aleatório.
# Se a variável EUREKA_ZONE existir, usa ela.
# Se não, usa localhost (valor padrão após os dois pontos)
eureka.instance.instance-id=${EUREKA_ZONE:http://localhost:8081/eureka}

# Porta em que a aplicação será executada.
# Ao usar "0", o Spring Boot atribui automaticamente uma porta aleatória disponível no sistema.
server.port=0

# Define o número de chamadas mais recentes consideradas
# no cálculo da taxa de falhas do Circuit Breaker.
resilience4j.circuitbreaker.instances.atualizaPedido.slidingWindowSize: 3

# Define a quantidade mínima de chamadas registradas
# antes que o Circuit Breaker passe a avaliar a taxa de falhas.
resilience4j.circuitbreaker.instances.atualizaPedido.minimumNumberOfCalls: 2

# Define o tempo em que o Circuit Breaker permanece no estado OPEN.
resilience4j.circuitbreaker.instances.atualizaPedido.waitDurationInOpenState: 60s